export const DISCOVER = {
  FETCH_DISCOVER_DATA: 'FETCH_DISCOVER_DATA',
  REFRESH_DISCOVER_DATA: 'REFRESH_DISCOVER_DATA',
  START_DATA_FETCHING: 'START_DATA_FETCHING',
  FINISH_DATA_FETCHING: 'FINISH_DATA_FETCHING',
}
